properties:
  browser: "chrome"
  environment: "prod"
  applitools: "true"
  envURL: "https://www.pams.co.nz"
  footerMenu: "Customer Service Contact Us FAQ Explore Pams Pams Pams Finest Pams Gluten Free Pams Organic Pams Superfoods Products Articles Recipe Finder Social and Ethical More from us About Foodstuffs South Island About Foodstuffs North Island Follow us Available at Copyright © 2021 Foodstuffs. All rights Reserved. Most Trusted Grocery Brand Terms and Conditions Privacy Notice"
  productsFinder: "https://www.pams.co.nz/product-finder#PamsProduct_e=0&PamsProduct_q="
  recipesFinder: "https://www.pams.co.nz/recipes/recipe-finder#Recipes_e=0&Recipes_q="
  articlesFinder: "https://www.pams.co.nz/articles#Articles_e=0&Articles_q="
  contactUsPageValidations: "First NameFirst Name is required.SurnameSurname is required.Email inputEmail input is required.Phone numberRegionMessageMessage is required."

  externalUrl:
    foodstuffSouthIsland: "https://www.foodstuffs-si.co.nz/"
    foodStuffNorthIsland: "https://www.foodstuffs.co.nz/"
    facebook: "https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fpams"
    instagram: "https://www.instagram.com/pams.nz/"
    instagramLogin: "https://www.instagram.com/accounts/login/"
    newWorld: "https://www.newworld.co.nz/"
    pakNSave: "https://www.paknsave.co.nz/"
    fourSquare: "https://www.foursquare.co.nz/"
    onTheSpot: "https://www.onthespot.co.nz/"
    raewardFresh: "https://raewardfresh.co.nz/"

  menu:
    Product Range: "/product-finder"
    Recipes:
      url: "/recipes"
      Search All Recipes: "/recipes/recipe-finder"
      Baking: "/recipes/baking-recipes"
      Breakfast: "/recipes/breakfast-recipes"
      Dinner: "/recipes/dinner-recipes"
      Gluten Free: "/recipes/gluten-free-recipes"
      Kid Friendly: "/recipes/kid-friendly-recipes"
      Ready in 20: "/recipes/ready-in-20-recipes"
      Sweet Treats: "/recipes/sweet-treats"
      Vegetarian: "/recipes/vegetarian-recipes"
      Browse all: "/recipes"
    Discover:
      url: "/discover"
      Pams: "/discover/pams"
      Pams Finest: "/discover/pams-finest"
      Pams Superfoods: "/discover/pams-superfoods"
      Pams Gluten Free: "/discover/pams-gluten-free"
      Pams Organic: "/discover/pams-organic"
      Pams Free Range: "/discover/pams-free-range"
      Pams Plant Based: "/discover/pams-plant-based"
      Browse all: "/discover"
    Social & Ethical: "/social-and-ethical"
    Articles: "/articles#Articles_e=0"
    Need help?: "/faq"
